# Generated by Django 4.1.3 on 2022-11-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categoriaId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenge.categoria'),
        ),
    ]
